name: bmi
description: BMI Calculator to learn about State Management.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  currency_text_input_formatter: ^2.2.3
  flutter:
    sdk: flutter
  flutter_web_router: ^1.0.2
  intl: ^0.19.0
  syncfusion_flutter_gauges: ^26.1.40

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
